name: Verify

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '20 4 * * *'

jobs:
  lint:
    name: Run PHP linter validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: firehed/lint-php-action@v1
